#!/usr/bin/env python3
"""
Simple HTTP server for JobCompass Web UI
Serves the web-ui directory on port 8000
"""

import http.server
import socketserver
import os

import ssl

PORT = 8085
DIRECTORY = os.path.dirname(os.path.abspath(__file__))

class MyHTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIRECTORY, **kwargs)
    
    
    def do_POST(self):
        # Proxy for trigger scrape to avoid Mixed Content (HTTPS -> HTTP)
        if self.path.startswith('/api/trigger-scrape'):
            import urllib.request
            import urllib.error
            
            # Target URL (internal docker service)
            target_url = 'http://scraper-service:8082/api/scraper/trigger/linkedin?maxResults=10&maxJobAgeDays=1'
            
            try:
                print(f"Proxying POST to: {target_url}")
                req = urllib.request.Request(target_url, method='POST')
                with urllib.request.urlopen(req) as response:
                    self.send_response(response.status)
                    for header, value in response.getheaders():
                        self.send_header(header, value)
                    self.end_headers()
                    self.wfile.write(response.read())
            except urllib.error.HTTPError as e:
                self.send_response(e.code)
                self.end_headers()
            except Exception as e:
                print(f"Proxy Error: {e}")
                self.send_response(500)
                self.end_headers()
        else:
            # For other POST requests (if any), default behavior (error usually)
            self.send_error(404, "Not Found")

    def end_headers(self):
        # Add CORS headers to allow API requests
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        super().end_headers()

if __name__ == '__main__':
    # Create SSL context
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    # These files will be generated by the Dockerfile
    context.load_cert_chain(certfile='/app/cert.pem', keyfile='/app/key.pem')

    class ThreadingSimpleServer(socketserver.ThreadingTCPServer):
        pass

    with ThreadingSimpleServer(("", PORT), MyHTTPRequestHandler) as httpd:
        httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
        
        print(f"🚀 JobCompass Web UI Server (HTTPS Enabled)")
        print(f"📡 Server running at: https://localhost:{PORT}")
        print(f"📂 Serving directory: {DIRECTORY}")
        print(f"🌐 Open in browser: https://localhost:{PORT}/index.html")
        print(f"\n💡 Note: You will sec a security warning because we use a self-signed certificate.")
        print(f"   Click 'Advanced' -> 'Proceed' to access the site.\n")
        print("Press Ctrl+C to stop the server\n")
        
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\n\n👋 Server stopped")
