#!/usr/bin/env python3
"""
Simple HTTP server for JobCompass Web UI
Serves the web-ui directory on port 8000
"""

import http.server
import socketserver
import os

import ssl

PORT = 8000
DIRECTORY = os.path.dirname(os.path.abspath(__file__))

class MyHTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIRECTORY, **kwargs)
    
    def end_headers(self):
        # Add CORS headers to allow API requests
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        super().end_headers()

if __name__ == '__main__':
    # Create SSL context
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    # These files will be generated by the Dockerfile
    context.load_cert_chain(certfile='/app/cert.pem', keyfile='/app/key.pem')

    class ThreadingSimpleServer(socketserver.ThreadingTCPServer):
        pass

    with ThreadingSimpleServer(("", PORT), MyHTTPRequestHandler) as httpd:
        httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
        
        print(f"🚀 JobCompass Web UI Server (HTTPS Enabled)")
        print(f"📡 Server running at: https://localhost:{PORT}")
        print(f"📂 Serving directory: {DIRECTORY}")
        print(f"🌐 Open in browser: https://localhost:{PORT}/index.html")
        print(f"\n💡 Note: You will sec a security warning because we use a self-signed certificate.")
        print(f"   Click 'Advanced' -> 'Proceed' to access the site.\n")
        print("Press Ctrl+C to stop the server\n")
        
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\n\n👋 Server stopped")
